<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon_server.ico</ApplicationIcon>
    <AssemblyName>RevitServerManager</AssemblyName>
    <RootNamespace>RevitServerManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon_server.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
