<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon_server.ico</ApplicationIcon>
    <AssemblyName>RevitServerManager</AssemblyName>
    <RootNamespace>RevitServerManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon_server.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <ProjectReference Include="..\RevitServerBridge\RevitServerBridge.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <EmbeddedResource Include="..\RevitServerBridge\bin\$(Configuration)\net48\RSBridge.exe" Link="Bridge\RSBridge.exe" Condition="Exists('..\RevitServerBridge\bin\$(Configuration)\net48\RSBridge.exe')" />
    <EmbeddedResource Include="..\RevitServerBridge\bin\$(Configuration)\net48\*.dll" Link="Bridge\%(Filename)%(Extension)" Condition="Exists('..\RevitServerBridge\bin\$(Configuration)\net48\RSBridge.exe')" />
  </ItemGroup>
</Project>
